### ISSUE TITLE
generate N5 fails

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/pybdv#37]
Hi,

I get a crash when wanting to generate a n5.

```python
import numpy as np
import pybdv
a=np.zeros((301,401,501))
a=np.uint8(a)
pybdv.make_bdv(a,'test1.n5')
```

leads to. 

```
Traceback (most recent call last):

  File "<ipython-input-1-22f42bb06f94>", line 5, in <module>
    pybdv.make_bdv(a,'test1.n5')

  File "/Users/schorb/code/pybdv/pybdv/converter.py", line 454, in make_bdv
    write_n5_metadata(data_path, factors, resolution, setup_id, timepoint,

  File "/Users/schorb/code/pybdv/pybdv/metadata.py", line 361, in write_n5_metadata
    _write_mdata(root, 'dataType', dtype)

  File "/Users/schorb/code/pybdv/pybdv/metadata.py", line 345, in _write_mdata
    g.attrs[key] = data

  File "/Users/schorb/miniconda3/envs/centrioles/lib/python3.9/site-packages/zarr/attrs.py", line 79, in __setitem__
    self._write_op(self._setitem_nosync, item, value)

  File "/Users/schorb/miniconda3/envs/centrioles/lib/python3.9/site-packages/zarr/attrs.py", line 73, in _write_op
    return f(*args, **kwargs)

  File "/Users/schorb/miniconda3/envs/centrioles/lib/python3.9/site-packages/zarr/attrs.py", line 90, in _setitem_nosync
    self._put_nosync(d)

  File "/Users/schorb/miniconda3/envs/centrioles/lib/python3.9/site-packages/zarr/attrs.py", line 112, in _put_nosync
    self.store[self.key] = json_dumps(d)

  File "/Users/schorb/miniconda3/envs/centrioles/lib/python3.9/site-packages/zarr/n5.py", line 130, in __setitem__
    raise ValueError("Can not set attribute %s, this is a reserved N5 keyword" % k)

ValueError: Can not set attribute dataType, this is a reserved N5 keyword
```

This is on Mac, Python 3.9, `zarr` used as N5 backend.

**Comment by martinschorb** [comment]
It works flawlessly when using `h5` as output format.

**Comment by constantinpape** [comment]
This is an issue in zarr, I made an issue about this a while ago but it seems to be still persisting:
https://github.com/zarr-developers/zarr-python/issues/693
